# Base ruleset, then override the noisy bits for GitHub Actions & templates
extends: default

ignore: |
  node_modules/
  dist/
  build/
  vendor/
  **/.venv/
  **/__pycache__/

rules:
  # Turn off line-length complaints (too noisy in CI)
  line-length: disable

  # GitHub Actions & templates do not require '---'
  document-start: disable

  # Indentation must be correct — YAML breaks if indentation is wrong
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false
    level: error   # safe to enforce — prevents broken YAML

  # Colon spacing issues break readability but not functionality
  # → escalate to error so formatting stays consistent
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: error

  # Enforce 2 spaces before inline comments
  # (‘key: value  # comment’)
  comments:
    min-spaces-from-content: 2
    level: error   # you explicitly want this enforced

  # Braces/brackets spacing impacts readability only
  # → keep as warnings to avoid pointless failures
  braces:
    max-spaces-inside: 1
    level: warning
  brackets:
    max-spaces-inside: 1
    level: warning

  # Trailing spaces are always bad
  trailing-spaces:
    level: error   # safe to enforce

  # Missing newline at EOF — stylistic only
  new-line-at-end-of-file:
    level: error

  # Empty lines — stylistic
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Common false-positives in Actions & templates
  truthy: disable
  octal-values: disable

