name: Local Stale Issue & Pull Request Handler

on:
  schedule:
    - cron: "35 5 * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale-issue-and-pull-request-handler:
    name: Stale Issue & Pull Request Handler
    uses: ./.github/workflows/reusable-stale-issue-and-pull-request-handler.yml

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - stale-issue-and-pull-request-handler
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  send-slack-notification:
    name: Send Slack Notification
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
