name: Local Link Checker

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/local-link-checker.yml"
      - "**/*.md"

  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/local-link-checker.yml"
      - "**/*.md"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  link-checker:
    name: Link Checker
    uses: ./.github/workflows/reusable-link-checker.yml
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - link-checker
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-workflow-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
