name: Local Secrets Scanner

on:
  push:
    branches:
      - "**"

  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  secrets-scanner:
    name: Secrets Scanner
    uses: ./.github/workflows/reusable-secrets-scanner.yml
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - secrets-scanner
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-workflow-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
