name: Local Workflow Runs Purger

on:
  workflow_dispatch:

  schedule:
    - cron: "33 3 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  workflow-run-purger:
    name: Workflow Run Purger
    uses: ./.github/workflows/reusable-workflow-run-purger.yml

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - workflow-run-purger
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-workflow-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
