name: Local Markdown Linter

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/local-markdown-linter.yml"
      - "**/*.md"
      - ".markdownlint.yml"
      - ".markdownlintignore"
      - ".markdownlint-cli2.jsonc"

  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/local-markdown-linter.yml"
      - "**/*.md"
      - ".markdownlint.yml"
      - ".markdownlintignore"
      - ".markdownlint-cli2.jsonc"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  markdown-linter:
    name: Markdown Linter
    uses: ./.github/workflows/reusable-markdown-linter.yml
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - markdown-linter
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-workflow-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
