name: 🔒 Local Ensure SHA-Pinned GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  ensure-sha-pinned:
    name: 🔒 Validate SHA-Pinned GitHub Actions
    uses: ./.github/workflows/reusable-ensure-sha-pinned-actions.yml

  workflow-summary:
    name: 📊 Workflow Summary
    needs:
      - ensure-sha-pinned
    if: always()
    uses: ./.github/workflows/reusable-check-jobs-status.yml
    with:
      ignore_jobs: "💬 Slack Notification"

  slack-notification:
    name: 💬 Slack Notification
    needs:
      - workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
      ignore_jobs: "📊 Workflow Summary,💬 Slack Notification"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
