name: Local YAML Linter

on:
  push:
    paths:
      - ".github/workflows/local-yaml-linter.yml"
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint.yml"

  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/local-yaml-linter.yml"
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint.yml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  yaml-linter:
    name: YAML Linter
    uses: ./.github/workflows/reusable-yaml-linter.yml
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - yaml-linter
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-workflow-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
