name: 🧹 Local Stale Issue & PR Handler

on:
  schedule:
    - cron: "35 5 * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    name: 🧹 Stale Issue & PR Handler
    uses: ./.github/workflows/reusable-stale.yml

  workflow-summary:
    name: 📊 Workflow Summary
    needs:
      - stale
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  slack-notification:
    name: 💬 Slack Notification
    needs:
      - workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
