name: Local Citation Validator

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "CITATION.cff"

  pull_request:
    branches:
      - "**"
    paths:
      - "CITATION.cff"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  citation-validator:
    name: Validate Citations File
    uses: ./.github/workflows/reusable-citation-validator.yml
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - citation-validator
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  send-slack-notification:
    name: Send Slack Notification
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
