name: Local Shell Scripts Linter

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/local-shell-script-linter.yml"
      - "**/*.sh"
      - "**/*.bash"
      - "**/*.bats"

  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/local-shell-script-linter.yml"
      - "**/*.sh"
      - "**/*.bash"
      - "**/*.bats"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  shell-scripts-linter:
    name: Shell Scripts Linter
    uses: ./.github/workflows/reusable-shell-script-linter.yml
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - shell-scripts-linter
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-workflow-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
