name: 🧪 Local Validate Citations File

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths:
      - "CITATION.cff"

  pull_request:
    branches:
      - "**"
    paths:
      - "CITATION.cff"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  validate:
    name: 🧪 Validate Citations File
    uses: ./.github/workflows/reusable-validate-citations-file.yml
    secrets: inherit

  workflow-summary:
    name: 📊 Workflow Summary
    needs:
      - validate
    if: always()
    uses: ./.github/workflows/reusable-check-jobs-status.yml
    with:
      ignore_jobs: "💬 Slack Notification"

  slack-notification:
    name: 💬 Slack Notification
    needs:
      - workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
      ignore_jobs: "📊 Workflow Summary,💬 Slack Notification"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
