name: 🧪 Local Python CI - send-to-slack.py

on:
  push:
    paths:
      - ".github/scripts/send-to-slack.py"
      - ".github/workflows/local-send-to-slack-ci.yml"

  pull_request:
    paths:
      - ".github/scripts/send-to-slack.py"
      - ".github/workflows/local-send-to-slack-ci.yml"

  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  python-ci:
    name: 🧪 Python CI
    uses: ./.github/workflows/reusable-python-ci.yml
    with:
      paths: ".github/scripts/send-to-slack.py"

  workflow-summary:
    name: 📊 Workflow Summary
    needs:
      - python-ci
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  slack-notification:
    name: 💬 Slack Notification
    needs:
      - workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
