name: 🧹 Local Purge Deprecated Workflow Runs

on:
  workflow_dispatch:

  schedule:
    - cron: "33 3 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  purge-deprecated-workflows:
    name: 🧹 Purge Deprecated Workflow Runs
    uses: ./.github/workflows/reusable-purge-deprecated-workflow-runs.yml

  workflow-summary:
    name: 📊 Workflow Summary
    needs:
      - purge-deprecated-workflows
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  slack-notification:
    name: 💬 Slack Notification
    needs:
      - workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
