name: 🧪 Local ShellCheck

on:
  push:
    branches:
      - "**"

  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  shellcheck:
    name: 🧪 ShellCheck
    uses: ./.github/workflows/reusable-shellcheck.yml
    secrets: inherit

  workflow-summary:
    name: 📊 Workflow Summary
    needs:
      - shellcheck
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  slack-notification:
    name: 💬 Slack Notification
    needs:
      - workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
