name: Local Dependabot Manager

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  dependabot-manager:
    name: Dependabot Manager
    uses: ./.github/workflows/reusable-dependabot-manager.yml
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - dependabot-manager
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  send-slack-notification:
    name: Send Slack Notification
    needs:
      - generate-workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-notifier.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
