name: Local Check check-jobs.py

on:
  push:
    paths:
      - ".github/scripts/check-jobs.py"
      - ".github/workflows/local-check-jobs-ci.yml"
      - ".github/workflows/reusable-check-jobs-status.yml"
  pull_request:
    paths:
      - ".github/scripts/check-jobs.py"
      - ".github/workflows/local-check-jobs-ci.yml"
      - ".github/workflows/reusable-check-jobs-status.yml"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  python-ci:
    name: Lint & type-check Python code
    uses: ./.github/workflows/reusable-python-ci.yml
    with:
      paths: ".github/scripts/check-jobs.py"

  status-check:
    name: Check Jobs Status
    needs:
      - python-ci
    if: always()
    uses: ./.github/workflows/reusable-check-jobs-status.yml
    with:
      ignore_jobs: "Slack Workflow Status"
      artifact_retention_days: 90

  slack-workflow-status:
    name: Slack Workflow Status
    needs:
      - status-check
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
      ignore_jobs: "Check Jobs Status"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
