name: 📚 Local Documentation Lint

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"

  pull_request:
    paths:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  awesomebot:
    name: 🔗 Awesomebot
    uses: ./.github/workflows/reusable-awesomebot.yml
    secrets: inherit

  markdown-lint:
    name: 📚 Markdown Lint
    uses: ./.github/workflows/reusable-markdown-lint.yml
    secrets: inherit

  yaml-lint:
    name: 📄 YAML Lint
    uses: ./.github/workflows/reusable-yaml-lint.yml
    secrets: inherit

  workflow-summary:
    name: 📊 Workflow Summary
    needs:
      - awesomebot
      - markdown-lint
      - yaml-lint
    if: always()
    uses: ./.github/workflows/reusable-workflow-summary.yml

  slack-notification:
    name: 💬 Slack Notification
    needs:
      - workflow-summary
    if: always()
    uses: ./.github/workflows/reusable-slack-workflow-status.yml
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
